### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by prologic** [thoj/go-ircevent#98]
I was able to trigger a panic:

```#!go
2017/11/07 00:53:29 <-- ERROR :quit
2017/11/07 00:53:29 ERROR (1) >> &irc.Event{Code:"ERROR", Raw:"ERROR :quit", Nick:"", Host:"", Source:"", User:"", Arguments:[]string{"quit"}, Connection:(*irc.Connection)(0xc42009a000)}
2017/11/07 00:53:29 Error, disconnected: EOF
panic: close of closed channel

goroutine 9 [running]:
github.com/thoj/go-ircevent.(*Connection).Disconnect(0xc42009a000)
	/Users/prologic/go/src/github.com/thoj/go-ircevent/irc.go:348 +0x1f4
created by github.com/thoj/go-ircevent.(*Connection).setupCallbacks.func1
	/Users/prologic/go/src/github.com/thoj/go-ircevent/irc_callback.go:141 +0x3e
```

**Comment by prologic** [comment]
#99 fixes this

**Comment by prologic** [comment]
#99 fixed this
